CLASS /eacm/bp_i_rpriepprv DEFINITION
  PUBLIC
  ABSTRACT
  FINAL FOR BEHAVIOR OF /eacm/i_rpriepprv.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS /eacm/bp_i_rpriepprv IMPLEMENTATION.
ENDCLASS.
